"""Change StripeAccount

Revision ID: 92280b102768
Revises: ca755cb6e59d
Create Date: 2025-05-24 16:36:46.750284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92280b102768'
down_revision: Union[str, None] = 'ca755cb6e59d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stripe_accounts', 'stripe_account_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stripe_accounts', 'stripe_account_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
