"""Add StripeAccounts

Revision ID: ca755cb6e59d
Revises: c95e63004c08
Create Date: 2025-05-24 15:52:02.469052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca755cb6e59d'
down_revision: Union[str, None] = 'c95e63004c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_account_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_accounts')
    # ### end Alembic commands ###
